# -*- mode: ruby -*-
# vi: set ft=ruby :

# One-time prep steps:
# vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.14"
# vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Workaround for newer versions of Vagrant, per:
# https://github.com/mitchellh/vagrant-aws/issues/566
class Hash
  def slice(*keep_keys)
    h = {}
    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }
    h
  end unless Hash.method_defined?(:slice)
  def except(*less_keys)
    slice(*keys - less_keys)
  end unless Hash.method_defined?(:except)
end

Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :aws do |aws, override|
        aws.aws_dir = ENV['HOME'] + "/.aws/"
        aws.aws_profile = ENV['VAGRANT_AWS_PROFILE']
        aws.region = ENV['VAGRANT_AWS_REGION']
        aws.tags = { 'Application' => ENV['VAGRANT_APPLICATION'] }
        aws.instance_type = ENV['VAGRANT_AWS_EC2_INSTANCE_TYPE']
        aws.associate_public_ip = true
        aws.keypair_name = ENV['VAGRANT_AWS_EC2_KEYPAIR']
        aws.ami = ENV['VAGRANT_AWS_AMI']
        aws.subnet_id = ENV['VAGRANT_AWS_SUBNET_ID']
        aws.security_groups = [ENV['VAGRANT_AWS_SECURITY_GROUP']]
        aws.block_device_mapping = [{
            'DeviceName' => "/dev/sdf",
            'VirtualName' => "ephemeral0",
            'Ebs.VolumeSize' => 100,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2'
        }]
        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.aws/" + ENV['VAGRANT_AWS_EC2_KEYPAIR'] + ".pem"
        aws.region_config ENV['VAGRANT_AWS_REGION'] do |region|
            region.spot_instance = true
            region.spot_max_price = ENV['VAGRANT_AWS_EC2_BID_PRICE']
        end
    end

    config.vm.provision "file", source: ENV['VAGRANT_AWS_CREDS'], destination: "/tmp/credentials"

    config.vm.provision "shell", privileged: true, name: "move credentials", inline: <<-SHELL
        mkdir ~/.aws && mv /tmp/credentials ~/.aws/ && chmod go-rwx ~/.aws/credentials
    SHELL

    config.vm.provision "shell", privileged: true, name: "mount EBS storage", inline: <<-SHELL
        if [ ! -d /work ] ; then
            dv=$(lsblk --output NAME,SIZE | awk '$2 == "100G"' | cut -f1 -d' ')
            mkfs -q -t ext4 /dev/${dv}
            mkdir /work
            mount /dev/${dv} /work/
            chmod a+w /work
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        yum update -q -y \
            && yum install -q -y wget curl tar which
    SHELL

    config.vm.provision "shell", privileged: true, name: "NCBI/GRCz10",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Danio_rerio NCBI GRCz10"

    config.vm.provision "shell", privileged: true, name: "Ensembl/BDGP6",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Drosophila_melanogaster Ensembl BDGP6"

    config.vm.provision "shell", privileged: true, name: "Ensembl/Galgal4",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Gallus_gallus Ensembl Galgal4"

    config.vm.provision "shell", privileged: true, name: "Ensembl/CHIMP2.1.4",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Pan_troglodytes Ensembl CHIMP2.1.4"

    config.vm.provision "shell", privileged: true, name: "NCBI/Rnor_6.0",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Rattus_norvegicus NCBI Rnor_6.0"

    config.vm.provision "shell", privileged: true, name: "Ensembl/AGPv4",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_igenomes.bash",
        args: "Zea_mays Ensembl AGPv4"
end
