# -*- mode: ruby -*-
# vi: set ft=ruby :

# One-time prep steps:
# vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.14"
# vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

ENV['VAG_DEFAULT_PROVIDER'] = 'aws'

eval File.read("Vagrantfile.hash_workaround")

Vagrant.configure("2") do |config|

    eval File.read("Vagrantfile.aws")

    config.vm.provision "file", source: ENV['VAG_CREDS'], destination: "/tmp/credentials"

    config.vm.provision "shell", privileged: true, name: "move credentials", path: "move_creds.bash"

    config.vm.provision "shell", privileged: true, name: "mount EBS storage",
        env: {"VOLUME_GB" => ENV['VAG_VOLUME_GB']}, path: "mount_ebs.bash"

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        yum update -q -y \
            && yum install -q -y wget curl tar which
    SHELL

    config.vm.provision "shell", privileged: true, name: "NCBI/GRCz10",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Danio_rerio NCBI GRCz10"

    config.vm.provision "shell", privileged: true, name: "Ensembl/BDGP6",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Drosophila_melanogaster Ensembl BDGP6"

    config.vm.provision "shell", privileged: true, name: "Ensembl/Galgal4",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Gallus_gallus Ensembl Galgal4"

    config.vm.provision "shell", privileged: true, name: "Ensembl/CHIMP2.1.4",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Pan_troglodytes Ensembl CHIMP2.1.4"

    config.vm.provision "shell", privileged: true, name: "NCBI/Rnor_6.0",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Rattus_norvegicus NCBI Rnor_6.0"

    config.vm.provision "shell", privileged: true, name: "Ensembl/AGPv4",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Zea_mays Ensembl AGPv4"

    config.vm.provision "shell", privileged: true, name: "Ensembl/WBcel235",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Caenorhabditis_elegans Ensembl WBcel235"

    config.vm.provision "shell", privileged: true, name: "NCBI/WS195",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Caenorhabditis_elegans NCBI WS195"

    config.vm.provision "shell", privileged: true, name: "Ensembl/CanFam3.1",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Canis_familiaris Ensembl CanFam3.1"

    config.vm.provision "shell", privileged: true, name: "NCBI/GRCm38",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Mus_musculus NCBI GRCm38"

    config.vm.provision "shell", privileged: true, name: "Ensembl/R64-1-1",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Saccharomyces_cerevisiae Ensembl R64-1-1"

    config.vm.provision "shell", privileged: true, name: "Ensembl/GRCh37",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Homo_sapiens Ensembl GRCh37"

    config.vm.provision "shell", privileged: true, name: "Ensembl/TAIR10",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_igenomes.bash",
        args: "Arabidopsis_thaliana Ensembl TAIR10"
end
