# -*- mode: ruby -*-
# vi: set ft=ruby :

# One-time prep steps:
# vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.14"
# vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Workaround for newer versions of Vagrant, per:
# https://github.com/mitchellh/vagrant-aws/issues/566
class Hash
  def slice(*keep_keys)
    h = {}
    keep_keys.each { |key| h[key] = fetch(key) if has_key?(key) }
    h
  end unless Hash.method_defined?(:slice)
  def except(*less_keys)
    slice(*keys - less_keys)
  end unless Hash.method_defined?(:except)
end

Vagrant.configure("2") do |config|

    config.vm.box = "dummy"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :aws do |aws, override|
        aws.aws_dir = ENV['HOME'] + "/.aws/"
        aws.aws_profile = ENV['VAGRANT_AWS_PROFILE']
        aws.region = ENV['VAGRANT_AWS_REGION']
        aws.tags = { 'Application' => ENV['VAGRANT_APPLICATION'] }
        aws.instance_type = ENV['VAGRANT_AWS_EC2_INSTANCE_TYPE']
        aws.associate_public_ip = true
        aws.keypair_name = ENV['VAGRANT_AWS_EC2_KEYPAIR']
        aws.ami = ENV['VAGRANT_AWS_AMI']
        aws.subnet_id = ENV['VAGRANT_AWS_SUBNET_ID']
        aws.security_groups = [ENV['VAGRANT_AWS_SECURITY_GROUP']]
        aws.block_device_mapping = [{
            'DeviceName' => "/dev/sdf",
            'VirtualName' => "ephemeral0",
            'Ebs.VolumeSize' => 50,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2'
        }]
        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.aws/" + ENV['VAGRANT_AWS_EC2_KEYPAIR'] + ".pem"
        aws.region_config ENV['VAGRANT_AWS_REGION'] do |region|
            region.spot_instance = true
            region.spot_max_price = ENV['VAGRANT_AWS_EC2_BID_PRICE']
        end
    end

    config.vm.provision "file", source: ENV['VAGRANT_AWS_CREDS'], destination: "/tmp/credentials"

    config.vm.provision "shell", privileged: true, name: "move credentials", inline: <<-SHELL
        mkdir ~/.aws && mv /tmp/credentials ~/.aws/ && chmod go-rwx ~/.aws/credentials
    SHELL

    config.vm.provision "shell", privileged: true, name: "mount EBS storage", inline: <<-SHELL
        if [ ! -d /work ] ; then
            dv=$(lsblk --output NAME,SIZE | awk '$2 == "50G"' | cut -f1 -d' ')
            mkfs -q -t ext4 /dev/${dv}
            mkdir /work
            mount /dev/${dv} /work/
            chmod a+w /work
        fi
    SHELL

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        yum update -q -y \
            && yum install -q -y make git wget curl tar gcc gcc-c++ which zlib zlib-devel
    SHELL

    config.vm.provision "shell", privileged: true, name: "install TBB",
        env: {"ARCH" => ENV['VAGRANT_AWS_EC2_ARCH']}, path: "install_tbb.bash"

    config.vm.provision "shell", privileged: true, name: "install BT2",
        env: {"ARCH" => ENV['VAGRANT_AWS_EC2_ARCH']}, path: "build_bt2.bash"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/263/795/GCF_002263795.1_ARS-UCD1.2/
    config.vm.provision "shell", privileged: true, name: "NCBI/ARS-UCD1.2",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Bos_taurus ARS-UCD1.2 GCF_002263795.1"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/035/GCF_000002035.6_GRCz11/
    config.vm.provision "shell", privileged: true, name: "NCBI/GRCz11",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Danio_rerio GRCz11 GCF_000002035.6"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/339/765/GCF_003339765.1_Mmul_10/
    config.vm.provision "shell", privileged: true, name: "NCBI/Mmul_10",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Macaca_mulatta Mmul_10 GCF_003339765.1"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/315/GCF_000002315.6_GRCg6a/
    config.vm.provision "shell", privileged: true, name: "NCBI/GRCg6a",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Gallus_gallus GRCg6a GCF_000002315.6"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/880/755/GCF_002880755.1_Clint_PTRv2/
    config.vm.provision "shell", privileged: true, name: "NCBI/Clint_PTRv2",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Pan_troglodytes Clint_PTRv2 GCF_002880755.1"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/425/GCF_000005425.2_Build_4.0/
    config.vm.provision "shell", privileged: true, name: "NCBI/Build_4.0",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Oryza_sativa Build_4.0 GCF_000005425.2"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/025/GCF_000003025.6_Sscrofa11.1/
    config.vm.provision "shell", privileged: true, name: "NCBI/Sscrofa11.1",
        env: {"BUCKET" => ENV['VAGRANT_BUCKET']}, path: "build_ncbi.bash",
        args: "Sus_scrofa Sscrofa11.1 GCF_000003025.6"
end
