# -*- mode: ruby -*-
# vi: set ft=ruby :

# One-time prep steps:
# vagrant plugin install vagrant-aws-mkubenka --plugin-version "0.7.2.pre.14"
# vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

ENV['VAG_DEFAULT_PROVIDER'] = 'aws'

eval File.read("Vagrantfile.hash_workaround")

Vagrant.configure("2") do |config|

    eval File.read("Vagrantfile.aws")

    config.vm.provision "file", source: ENV['VAG_CREDS'], destination: "/tmp/credentials"

    config.vm.provision "shell", privileged: true, name: "move credentials", path: "move_creds.bash"

    config.vm.provision "shell", privileged: true, name: "mount EBS storage",
        env: {"VOLUME_GB" => ENV['VAG_VOLUME_GB']}, path: "mount_ebs.bash"

    config.vm.provision "shell", privileged: true, name: "install Linux packages", inline: <<-SHELL
        yum update -q -y \
            && yum install -q -y make git wget curl tar gcc gcc-c++ which zlib zlib-devel
    SHELL

    config.vm.provision "shell", privileged: true, name: "install TBB",
        env: {"ARCH" => ENV['VAG_EC2_ARCH']}, path: "install_tbb.bash"

    config.vm.provision "shell", privileged: true, name: "install BT2",
        env: {"ARCH" => ENV['VAG_EC2_ARCH']}, path: "build_bt2.bash"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/263/795/GCF_002263795.1_ARS-UCD1.2/
    config.vm.provision "shell", privileged: true, name: "NCBI/ARS-UCD1.2",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "ARS-UCD1.2 GCF_002263795.1 Bos_taurus"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/002/285/GCA_000002285.3_canfam4/
    config.vm.provision "shell", privileged: true, name: "NCBI/canfam4",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "canfam4 GCA_000002285.3 Canis_familiaris"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/635/GCF_000001635.27_GRCm39/
    config.vm.provision "shell", privileged: true, name: "NCBI/GRCm39",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "GRCm39 GCF_000001635.27 Mus_musculus"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/035/GCF_000002035.6_GRCz11/
    config.vm.provision "shell", privileged: true, name: "NCBI/GRCz11",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "GRCz11 GCF_000002035.6 Danio_rerio"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/339/765/GCF_003339765.1_Mmul_10/
    config.vm.provision "shell", privileged: true, name: "NCBI/Mmul_10",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Mmul_10 GCF_003339765.1 Macaca_mulatta"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/902/167/145/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0/GCF_902167145.1_Zm-B73-REFERENCE-NAM-5.0_genomic.fna.gz
    config.vm.provision "shell", privileged: true, name: "NCBI/Zm-B73-REFERENCE-NAM-5.0",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Zm-B73-REFERENCE-NAM-5.0 GCF_902167145.1 Zea_mays"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/315/GCF_000002315.6_GRCg6a/
    config.vm.provision "shell", privileged: true, name: "NCBI/GRCg6a",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "GRCg6a GCF_000002315.6 Gallus_gallus"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/880/755/GCF_002880755.1_Clint_PTRv2/
    config.vm.provision "shell", privileged: true, name: "NCBI/Clint_PTRv2",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Clint_PTRv2 GCF_002880755.1 Pan_troglodytes"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/425/GCF_000005425.2_Build_4.0/
    config.vm.provision "shell", privileged: true, name: "NCBI/Build_4.0",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Build_4.0 GCF_000005425.2 Oryza_sativa"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/003/025/GCF_000003025.6_Sscrofa11.1/
    config.vm.provision "shell", privileged: true, name: "NCBI/Sscrofa11.1",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Sscrofa11.1 GCF_000003025.6 Sus_scrofa"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/300/595/GCA_002300595.1_Dmel_A4_1.0/
    config.vm.provision "shell", privileged: true, name: "NCBI/Dmel_A4_1.0",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "Dmel_A4_1.0 GCA_002300595.1 Drosophila_melanogaster"

    # https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.4_TAIR10.1/GCF_000001735.4_TAIR10.1_genomic.fna.gz
    config.vm.provision "shell", privileged: true, name: "NCBI/TAIR10.1",
        env: {"BUCKET" => ENV['VAG_BUCKET']}, path: "build_ncbi.bash",
        args: "TAIR10.1 GCF_000001735.4 Arabidopsis_thaliana"

end
